service: duckFeed
frameworkVersion: "=1.39.1"

provider:
  name: aws
  runtime: nodejs6.10
  profile: default # AWS CLI profile name
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:*:*"
  environment: 
    APP_SECRET: ${file(./config.yml):${self:custom.stage}.APP_SECRET}
    DB_PREFIX: ${file(./config.yml):${self:custom.stage}.DB_PREFIX}

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  DB_PREFIX: ${file(./config.yml):${self:custom.stage}.DB_PREFIX}
  dynamodb:  
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:custom.DB_PREFIX}-duckFeed
            sources: [./offline/migrations/duckFeed-seed.json]

functions:
  saveFeed:
    handler: handler.saveFeed
    events:
    - http:
        method: POST
        path: feeds
        cors: true
resources:
  Resources: ${file(offline/migrations/duckFeed.yml)}

package:
  exclude:
    - node_modules/dynamodb-localhost/**
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**

